# https://github.com/macro0630/python_edu

# Neural Networks and Deep Learning

### 아래 기초에 대해 먼저 학습합니다.

### https://drive.google.com/open?id=1TdlnkFU4Zukw2ajdxm7HE8BQts0pdoP_1RDc6XDKZmg

## Keras 환경 구성 및 설치

아나콘다 프롬프트에서 다음처럼 한다. 다 설치되면 주피터 노트북을 다시 실행한다.

케라스는 파이썬 3.6에서 동작하므로, 콘다 가상환경을 만들어 준다.

$ conda create --name ai python=3.6 tensorflow keras

가상환경을 실행한다.

$ conda activate ai

머신러닝 관련 라이브러리 설치해 준다.

$ conda install  numpy scipy matplotlib ipython scikit-learn pandas pillow jupyter



In [1]:
import keras

Using TensorFlow backend.


In [25]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [26]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [27]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [28]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [29]:
X = dataset.iloc[ : , 3: -1].values

In [30]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [31]:
y = dataset.iloc[: , -1].values

In [32]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [33]:
X.shape

(10000, 10)

In [34]:
y.shape

(10000,)

In [35]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [37]:
label_e_1 = LabelEncoder()

In [38]:
X[:, 1] = label_e_1.fit_transform(X[:, 1])

In [39]:
label_e_2 = LabelEncoder()

In [40]:
X[:, 2] = label_e_2.fit_transform(X[:,2])

In [41]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [42]:
from sklearn.compose import ColumnTransformer

In [43]:
ct = ColumnTransformer(
        [('one_hot_encode' , OneHotEncoder(categories='auto'), [ 1 ]   ) ],
        remainder='passthrough'
)

In [44]:
X = np.array(ct.fit_transform(X), dtype = np.float)

In [47]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [48]:
X.shape

(10000, 12)

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                   random_state = 3)

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sc = StandardScaler()

In [53]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
y_train.shape

(8000,)

In [56]:
y_train = y_train.reshape(y_train.shape[0], 1)

In [57]:
y_train.shape

(8000, 1)

In [58]:
y_test = y_test.reshape(y_test.shape[0], 1)

In [59]:
y_test.shape

(2000, 1)

In [60]:
from keras.models import Sequential

In [61]:
from keras.layers import Dense

In [62]:
classifier = Sequential()

W0908 15:22:00.340288  7012 deprecation_wrapper.py:119] From E:\Anaconda3\envs\ai\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [63]:
classifier.add(  Dense(output_dim = 6, init='uniform', 
                      activation = 'relu', input_dim = 12) )

E:\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6, kernel_initializer="uniform")`
  
W0908 15:24:47.945996  7012 deprecation_wrapper.py:119] From E:\Anaconda3\envs\ai\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0908 15:24:47.981197  7012 deprecation_wrapper.py:119] From E:\Anaconda3\envs\ai\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [64]:
classifier.add( Dense(output_dim = 8, init = 'uniform', activation='relu') )

E:\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [65]:
classifier.add( Dense(output_dim = 1, init="uniform", activation='sigmoid'))

E:\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [66]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', 
                   metrics=['accuracy'])

W0908 15:32:13.175526  7012 deprecation_wrapper.py:119] From E:\Anaconda3\envs\ai\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0908 15:32:13.221127  7012 deprecation_wrapper.py:119] From E:\Anaconda3\envs\ai\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0908 15:32:13.228128  7012 deprecation.py:323] From E:\Anaconda3\envs\ai\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [67]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

E:\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.
W0908 15:33:27.063892  7012 deprecation_wrapper.py:119] From E:\Anaconda3\envs\ai\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4769 - acc: 0.7947
Epoch 2/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.4283 - acc: 0.7947
Epoch 3/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4207 - acc: 0.8051
Epoch 4/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4167 - acc: 0.8262
Epoch 5/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.4141 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.4122 - acc: 0.8299
Epoch 7/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.4106 - acc: 0.8289
Epoch 8/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.4099 - acc: 0.8315
Epoch 9/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4087 - acc: 0.8330
Epoch 10/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4079 - acc: 0.8321
Epoch 11

8000/8000 [==============================] - 1s 90us/step - loss: 0.3943 - acc: 0.8384
Epoch 84/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3943 - acc: 0.8370
Epoch 85/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3932 - acc: 0.8366
Epoch 86/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3942 - acc: 0.8371
Epoch 87/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3936 - acc: 0.8375
Epoch 88/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3938 - acc: 0.8379
Epoch 89/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.3934 - acc: 0.8374
Epoch 90/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3937 - acc: 0.8377
Epoch 91/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3939 - acc: 0.8354
Epoch 92/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.3934 - acc: 0.8369
Epoch 93/100


In [68]:
y_pred = classifier.predict(X_test)

In [70]:
y_pred = (y_pred > 0.5)

In [71]:
from sklearn.metrics import confusion_matrix

In [72]:
cm = confusion_matrix(y_test, y_pred)

In [73]:
cm

array([[1531,   74],
       [ 240,  155]], dtype=int64)

In [74]:
score = classifier.evaluate(X_test, y_test)

2000/2000 [==============================] - 0s 51us/step


In [75]:
print('loss : ', score[0])
print('accuracy : ', score[1])

loss :  0.40117615580558774
accuracy :  0.843
